#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Dec 17 17:03:56 CET 2021
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim num_capture_4bit_TB_behav -key {Behavioral:sim_1:Functional:num_capture_4bit_TB} -tclbatch num_capture_4bit_TB.tcl -protoinst "protoinst_files/design_1.protoinst" -view /media/kamranpoladov/db5e1c1b-558e-4f71-be03-2e729f28bda5/KUL/ddc/DDC-Lab-Final/ASCII_Displayer_V3/ASCII_Displayer_V3.srcs/sim_1/imports/Hexadecimal_Editor/num_capture_4bit_TB_behav.wcfg -log simulate.log"
xsim num_capture_4bit_TB_behav -key {Behavioral:sim_1:Functional:num_capture_4bit_TB} -tclbatch num_capture_4bit_TB.tcl -protoinst "protoinst_files/design_1.protoinst" -view /media/kamranpoladov/db5e1c1b-558e-4f71-be03-2e729f28bda5/KUL/ddc/DDC-Lab-Final/ASCII_Displayer_V3/ASCII_Displayer_V3.srcs/sim_1/imports/Hexadecimal_Editor/num_capture_4bit_TB_behav.wcfg -log simulate.log

