@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Dec 14 23:30:42 +0100 2021
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim num_capture_4bit_TB_behav -key {Behavioral:sim_1:Functional:num_capture_4bit_TB} -tclbatch num_capture_4bit_TB.tcl -view C:/Users/arthu/DigitalConceptsLab/Lab5/Hexadecimal_Editor_V3/Hexadecimal_Editor_V3.srcs/sim_1/imports/Hexadecimal_Editor/num_capture_4bit_TB_behav.wcfg -log simulate.log"
call xsim  num_capture_4bit_TB_behav -key {Behavioral:sim_1:Functional:num_capture_4bit_TB} -tclbatch num_capture_4bit_TB.tcl -view C:/Users/arthu/DigitalConceptsLab/Lab5/Hexadecimal_Editor_V3/Hexadecimal_Editor_V3.srcs/sim_1/imports/Hexadecimal_Editor/num_capture_4bit_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
